# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Htweets',
            fields=[
                ('tweet_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('tweet_date', models.DateTimeField()),
                ('tweet_source', models.TextField()),
                ('tweet_favour_count', models.CharField(max_length=200)),
                ('tweet_retweet_cnt', models.CharField(max_length=200)),
                ('tweet_text', models.TextField()),
            ],
        ),
    ]
