# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermtweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=None)),
                ('tweet_date', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 9, 22, 21, 163042, tzinfo=utc))),
                ('tweet_favour_count', models.CharField(default=None, max_length=200)),
                ('tweet_recount', models.BigIntegerField(default=None)),
                ('tweet_text', models.TextField(default=None)),
                ('tweet_timestamp', models.TimeField(default=datetime.datetime(2017, 4, 10, 9, 22, 21, 163637, tzinfo=utc))),
                ('tweet_media_entities', models.URLField(default=None)),
            ],
        ),
    ]
