# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hermtweets', '0008_auto_20170410_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermtweets',
            name='tweet_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hermtweets',
            name='tweet_timestamp',
            field=models.BigIntegerField(),
        ),
    ]
