# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Hermtweets', '0017_auto_20170410_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermtweets',
            name='tweet_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 12, 48, 41, 639270, tzinfo=utc)),
        ),
    ]
