# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Htweets2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htweets2',
            name='tweet_analysis',
            field=models.TextField(blank=True),
        ),
    ]
