# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Htweets2', '0002_htweets2_tweet_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htweets2',
            name='tweet_analysis',
        ),
    ]
