# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Htweets2', '0003_remove_htweets2_tweet_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='htweets2',
            name='tweet_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
