# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Htweets2', '0004_htweets2_tweet_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htweets2',
            name='tweet_score',
        ),
    ]
