# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Htweets2', '0005_remove_htweets2_tweet_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='htweets2',
            name='tweet_score',
            field=models.TextField(blank=True),
        ),
    ]
